version: '3'
networks:
  traefik:
    external: true
services:
  masseydebate:
    labels:
      - "traefik.docker.network: traefik"
      - "traefik.frontend.rule=Host:masseydebate.com"
      - "traefik.enable=true"
    networks:
      - traefik
    restart: always
    logging:
      driver: "fluentd"
      options:
        tag: website.{{.ImageName}}/{{.ID}}
    image: "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"