version: '3'
networks:
  traefik:
    external: true
services:
  masseydebate:
    labels:
      - "traefik.docker.network: traefik"
      - "traefik.frontend.rule=Host:masseydebate.com"
      - "traefik.enable=true"
    networks:
      - traefik
    image: "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
